plugins {
    id 'java'
    id 'com.zeroc.slice-tools' version '3.8.2'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.zeroc:ice:3.8.3'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.register('runServer', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'Server'
}

tasks.register('runClient', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'Client'
}
